import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const SUPABASE_URL='https://uxmlmyhiagjefuufanyg.supabase.co';
const SUPABASE_KEY='sb_publishable_wAajSubj-zZE7kFh7EAxog_2FxCrs6Z';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const DRAFT='vencivo_ai_builder_v2';

function toast(text){let el=document.getElementById('vencivoImplantToast');if(!el){el=document.createElement('div');el.id='vencivoImplantToast';Object.assign(el.style,{position:'fixed',left:'50%',bottom:'20px',transform:'translateX(-50%)',zIndex:'99999',padding:'12px 16px',borderRadius:'12px',background:'#111a2a',color:'#fff',border:'1px solid #ffffff22',boxShadow:'0 15px 50px #0008',font:'600 14px system-ui',maxWidth:'90vw',textAlign:'center'});document.body.appendChild(el)}el.textContent=text;el.style.display='block';clearTimeout(window._vt);window._vt=setTimeout(()=>el.style.display='none',2800)}

function hookAgentCreation(){const original=window.fetch.bind(window);window.fetch=async function(input,init={}){const url=typeof input==='string'?input:(input?.url||'');const response=await original(input,init);if(url.includes('/api/agents')&&init?.method==='POST'){response.clone().json().then(p=>{const id=p?.agent?.id;if(id){window._vencivoAgentId=id;const b=document.getElementById('implant');if(b)b.dataset.agentId=id}}).catch(()=>{});}return response}}

function getAgentId(){const b=document.getElementById('implant');const direct=window._vencivoAgentId||b?.dataset?.agentId;if(direct)return direct;const href=document.getElementById('openAgent')?.getAttribute('href')||'';try{const id=new URL(href,location.href).searchParams.get('id');if(id)return id}catch{}return new URLSearchParams(location.search).get('agent')||''}

function styleBuilder(){if(document.getElementById('vencivo-builder-polish'))return;const s=document.createElement('style');s.id='vencivo-builder-polish';s.textContent=`.builder{font-size:16px}.builder .field label{font-size:14px}.builder .input,.builder .select,.builder .textarea{font-size:15px;padding:11px 12px}.builder .hint{font-size:12px}.builder .check{font-size:13px}.builder .actions{gap:9px}.builder .actions .btn{font-size:14px;padding:10px 14px}#implant{order:10!important;width:100%!important;min-height:52px!important;margin-top:8px!important;padding:14px 18px!important;border:0!important;border-radius:13px!important;background:linear-gradient(135deg,#25d366,#16a34a)!important;color:#fff!important;font-size:16px!important;font-weight:950!important;box-shadow:0 10px 28px #16a34a35!important}#openAgent{order:1;font-size:13px!important;opacity:.78}.builder .actions #implant{flex-basis:100%}.preview #send{width:auto;min-width:92px;font-weight:900}.preview .msg{font-size:15px;line-height:1.55}`;document.head.appendChild(s)}

function normalize(){const b=document.getElementById('implant');if(b){b.textContent='IMPLANTAR NO WHATSAPP';b.removeAttribute('href');b.removeAttribute('target');b.setAttribute('aria-label','Implantar este agente no WhatsApp')}const send=document.getElementById('send');if(send)send.textContent='ENVIAR'}

function patchNewAgent(){const b=document.getElementById('newBtn');if(!b)return;b.onclick=(e)=>{e.preventDefault();e.stopPropagation();localStorage.removeItem(DRAFT);location.reload()}}

async function checkout(){const b=document.getElementById('implant'),agentId=getAgentId();if(!agentId){toast('ID do agente ainda não disponível. Clique novamente em IMPLANTAR NO WHATSAPP.');return}const {data,error}=await supabase.auth.getSession(),session=data?.session;if(error||!session?.access_token){toast('Sua sessão não está ativa. Faça login novamente.');setTimeout(()=>location.href='conta.html',1200);return}b.textContent='PREPARANDO PAGAMENTO...';b.style.pointerEvents='none';try{const phone=document.getElementById('whatsapp')?.value?.trim()||'',name=session.user?.user_metadata?.full_name||session.user?.email||'Cliente VENCIVO';const r=await fetch('/api/asaas-checkout',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session.access_token},body:JSON.stringify({agent_id:agentId,name,phone})});const p=await r.json().catch(()=>({}));if(!r.ok||!p.checkout_url)throw new Error(p.error||'Não foi possível iniciar o pagamento agora.');toast('Checkout preparado. Redirecionando...');location.href=p.checkout_url}catch(e){toast(e.message||'Não foi possível iniciar o pagamento agora.');b.textContent='IMPLANTAR NO WHATSAPP';b.style.pointerEvents=''}}

function patchBuilder(){hookAgentCreation();styleBuilder();normalize();patchNewAgent();const b=document.getElementById('implant');if(!b)return;if(!b.dataset.vencivoPatched){b.dataset.vencivoPatched='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();checkout()},true)}const observer=new MutationObserver(()=>normalize());observer.observe(b,{attributes:true,childList:true,subtree:true})}

function patchWhatsapp(){const original=window.fetch.bind(window);window.fetch=async function(input,init={}){const url=typeof input==='string'?input:(input?.url||'');if(url.includes('/api/whatsapp-activate')&&init?.method==='POST'){const {data}=await supabase.auth.getSession();if(data?.session?.access_token)init={...init,headers:{...(init.headers||{}),Authorization:'Bearer '+data.session.access_token}}}return original(input,init)}}

function run(){if(location.pathname.endsWith('/ia-v2.html'))patchBuilder();if(location.pathname.endsWith('/whatsapp-config.html'))patchWhatsapp()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();