import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const SUPABASE_URL='https://uxmlmyhiagjefuufanyg.supabase.co';
const SUPABASE_KEY='sb_publishable_wAajSubj-zZE7kFh7EAxog_2FxCrs6Z';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const DRAFT='vencivo_ai_builder_v2';
let previewHistory=[];
let previewSession=crypto.randomUUID?crypto.randomUUID():String(Date.now());

function toast(text){let el=document.getElementById('vencivoImplantToast');if(!el){el=document.createElement('div');el.id='vencivoImplantToast';Object.assign(el.style,{position:'fixed',left:'50%',bottom:'20px',transform:'translateX(-50%)',zIndex:'99999',padding:'12px 16px',borderRadius:'12px',background:'#111a2a',color:'#fff',border:'1px solid #ffffff22',boxShadow:'0 15px 50px #0008',font:'600 14px system-ui',maxWidth:'90vw',textAlign:'center'});document.body.appendChild(el)}el.textContent=text;el.style.display='block';clearTimeout(window._vt);window._vt=setTimeout(()=>el.style.display='none',2800)}

function styleBuilder(){if(document.getElementById('vencivo-builder-polish'))return;const s=document.createElement('style');s.id='vencivo-builder-polish';s.textContent=`.builder{font-size:16px}.builder .field label{font-size:14px}.builder .input,.builder .select,.builder .textarea{font-size:15px;padding:11px 12px}.builder .hint{font-size:12px}.builder .check{font-size:13px}.builder .actions{gap:9px}.builder .actions .btn{font-size:14px;padding:10px 14px}#implant{order:10!important;width:100%!important;min-height:52px!important;margin-top:8px!important;padding:14px 18px!important;border:0!important;border-radius:13px!important;background:linear-gradient(135deg,#25d366,#16a34a)!important;color:#fff!important;font-size:16px!important;font-weight:950!important;box-shadow:0 10px 28px #16a34a35!important}.preview #send{width:auto;min-width:92px;font-weight:900}.preview .msg{font-size:15px;line-height:1.55}`;document.head.appendChild(s)}

function normalize(){const b=document.getElementById('implant');if(b){if(b.textContent!=='IMPLANTAR NO WHATSAPP')b.textContent='IMPLANTAR NO WHATSAPP';if(b.hasAttribute('href'))b.removeAttribute('href');if(b.hasAttribute('target'))b.removeAttribute('target');if(b.getAttribute('aria-label')!=='Implantar este agente no WhatsApp')b.setAttribute('aria-label','Implantar este agente no WhatsApp')}const send=document.getElementById('send');if(send&&send.textContent!=='ENVIAR')send.textContent='ENVIAR'}

function patchNewAgent(){const b=document.getElementById('newBtn');if(!b)return;if(b.dataset.vencivoNewPatched==='1')return;b.dataset.vencivoNewPatched='1';b.onclick=(e)=>{e.preventDefault();e.stopPropagation();localStorage.removeItem(DRAFT);localStorage.removeItem('vencivo_ai_current_agent');location.href='ia-v2.html?novo=1'}}

function findCreateButton(){return [...document.querySelectorAll('button')].find(b=>/criar meu agente/i.test((b.textContent||'').trim()))||[...document.querySelectorAll('button')].find(b=>/criar.*agente/i.test((b.textContent||'').trim())&&b.closest('#f2'))}

async function readKnowledge(){const input=document.getElementById('file');const file=input?.files?.[0];if(!file)return {text:'',name:''};if(file.size>81920)throw new Error('Arquivo acima de 80 KB.');return {text:(await file.text()).slice(0,80000),name:file.name}}

function buildSystemPrompt(){const company=document.getElementById('empresa')?.value.trim()||'',segment=document.getElementById('segmento')?.value.trim()||'',services=document.getElementById('oferta')?.value.trim()||'',hours=document.getElementById('horario')?.value.trim()||'',city=document.getElementById('cidade')?.value.trim()||'';const caps=[...document.querySelectorAll('#checks input:checked')].map(x=>x.value);const personality=document.getElementById('tom')?.value||'';const objective=document.getElementById('objetivo')?.value||'';return `Você é o assistente virtual ${company} AI, da empresa ${company}, segmento ${segment}.\n\nINFORMAÇÕES OFICIAIS:\nCidade/região: ${city||'não informado'}\nHorário: ${hours||'não informado'}\nProdutos e serviços: ${services}\n\nFUNÇÕES AUTORIZADAS: ${caps.join(', ')||'Responder dúvidas'}.\nPERSONALIDADE: ${personality}.\nOBJETIVO: ${objective}.\n\nREGRAS: use somente informações fornecidas pela empresa; nunca invente preços, horários, serviços, disponibilidade ou políticas; quando não souber, diga claramente e encaminhe para humano quando apropriado; responda em português do Brasil; não solicite senhas, códigos ou dados bancários; seja natural, cordial e objetivo.`}

function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c))}

function addPreviewMessage(type,text){const messages=document.getElementById('messages');if(!messages)return;const d=document.createElement('div');d.className='msg '+type;d.textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight;return d}

function bindPreviewChat(id){const input=document.getElementById('chatInput'),send=document.getElementById('send');if(!input||!send)return;previewHistory=[];previewSession=crypto.randomUUID?crypto.randomUUID():String(Date.now());input.disabled=false;input.placeholder='Digite como um cliente...';send.disabled=false;send.textContent='ENVIAR';const sendMessage=async()=>{const q=input.value.trim();if(!q||!id||send.dataset.busy==='1')return;send.dataset.busy='1';input.value='';addPreviewMessage('user',q);send.disabled=true;const thinking=addPreviewMessage('bot','Pensando...');previewHistory.push({role:'user',content:q});try{const r=await fetch('/api/agent-chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({agent_id:id,session_id:previewSession,nova_mensagem:q,historico_mensagens:previewHistory}),cache:'no-store'});const p=await r.json().catch(()=>({}));thinking?.remove();if(!r.ok)throw new Error(p.error||'Não foi possível responder.');addPreviewMessage('bot',p.reply);previewHistory.push({role:'assistant',content:p.reply})}catch(e){thinking?.remove();addPreviewMessage('bot',e.message||'Não foi possível responder agora.')}finally{send.dataset.busy='0';send.disabled=false;input.focus()}};send.onclick=sendMessage;input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();sendMessage()}};document.querySelectorAll('.suggest button').forEach(btn=>{btn.onclick=()=>{if(input.disabled)return;input.value=btn.textContent||'';sendMessage()}})}

function syncCreatedAgent(agent){const id=agent?.id;if(!id)return;window._vencivoAgentId=id;localStorage.setItem('vencivo_ai_current_agent',id);const displayName=agent.agent_name||`${document.getElementById('empresa')?.value.trim()||'Seu agente'} AI`;const name=document.getElementById('agentName'),avatar=document.getElementById('avatar'),messages=document.getElementById('messages');if(name)name.textContent=displayName;if(avatar)avatar.textContent=displayName.replace(/\s+/g,'').slice(0,2).toUpperCase();if(messages){messages.innerHTML='';addPreviewMessage('bot',`Olá! Eu sou o assistente virtual da ${document.getElementById('empresa')?.value.trim()||displayName.replace(/ AI$/,'')} AI. Como posso ajudar?`)}const open=document.getElementById('openAgent');if(open)open.href=`agente.html?id=${encodeURIComponent(id)}`;const implant=document.getElementById('implant');if(implant)implant.dataset.agentId=id;bindPreviewChat(id)}

async function stableCreate(){const button=findCreateButton();if(!button)return;if(button.dataset.stableCreate==='1')return;button.dataset.stableCreate='1';button.addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();if(button.dataset.busy==='1')return;button.dataset.busy='1';const original=button.textContent;button.textContent='CRIANDO AGENTE...';button.disabled=true;try{const company=document.getElementById('empresa')?.value.trim();const segment=document.getElementById('segmento')?.value;const services=document.getElementById('oferta')?.value.trim();if(!company||!segment||!services)throw new Error('Preencha empresa, segmento e produtos/serviços antes de criar o agente.');const knowledge=await readKnowledge();const {data}=await supabase.auth.getSession();const token=data?.session?.access_token||'';const payload={company_name:company,agent_name:`${company} AI`,segment,whatsapp:document.getElementById('whatsapp')?.value.trim()||'',city_region:document.getElementById('cidade')?.value.trim()||'',services,business_hours:document.getElementById('horario')?.value.trim()||'',capabilities:[...document.querySelectorAll('#checks input:checked')].map(x=>x.value),personality:document.getElementById('tom')?.value||'',objective:document.getElementById('objetivo')?.value||'',system_prompt:buildSystemPrompt(),knowledge_text:knowledge.text,knowledge_file_name:knowledge.name};const headers={'Content-Type':'application/json'};if(token)headers.Authorization='Bearer '+token;const response=await fetch('/api/agents',{method:'POST',headers,body:JSON.stringify(payload),cache:'no-store'});let result={};try{result=await response.json()}catch{}if(!response.ok||!result.agent?.id)throw new Error(result.error||`Não foi possível criar o agente (${response.status}).`);syncCreatedAgent(result.agent);const summary=document.getElementById('summary');if(summary)summary.innerHTML=`<div><b>Empresa</b><span>${escapeHtml(result.agent.company_name)}</span></div><div><b>Segmento</b><span>${escapeHtml(result.agent.segment)}</span></div><div><b>Base de conhecimento</b><span>${knowledge.text?'Enviada':'Não enviada'}</span></div><div><b>Status</b><span>Demonstração ativa</span></div>`;if(typeof window.show==='function')window.show(3);toast('Agente criado com sucesso.')}catch(err){console.error('Stable agent creation:',err);toast(err.message||'Não foi possível criar o agente agora.');button.textContent=original;button.disabled=false;button.dataset.busy='0';return}button.textContent='AGENTE CRIADO ✓';setTimeout(()=>{button.dataset.busy='0';button.disabled=false;button.textContent=original},1200)},true)}

async function checkout(){const b=document.getElementById('implant'),agentId=b?.dataset?.agentId||window._vencivoAgentId||localStorage.getItem('vencivo_ai_current_agent');if(!agentId){toast('ID do agente ainda não disponível. Crie o agente novamente.');return}const {data,error}=await supabase.auth.getSession(),session=data?.session;if(error||!session?.access_token){toast('Sua sessão não está ativa. Faça login novamente.');setTimeout(()=>location.href='conta.html',1200);return}b.textContent='PREPARANDO PAGAMENTO...';b.style.pointerEvents='none';try{const phone=document.getElementById('whatsapp')?.value?.trim()||'',name=session.user?.user_metadata?.full_name||session.user?.email||'Cliente VENCIVO';const r=await fetch('/api/asaas-checkout',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session.access_token},body:JSON.stringify({agent_id:agentId,name,phone}),cache:'no-store'});const p=await r.json().catch(()=>({}));if(!r.ok||!p.checkout_url)throw new Error(p.error||'Não foi possível iniciar o pagamento agora.');location.href=p.checkout_url}catch(e){toast(e.message||'Não foi possível iniciar o pagamento agora.');b.textContent='IMPLANTAR NO WHATSAPP';b.style.pointerEvents=''}}

function patchBuilder(){styleBuilder();normalize();patchNewAgent();stableCreate();const b=document.getElementById('implant');if(b&&!b.dataset.vencivoPatched){b.dataset.vencivoPatched='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();checkout()},true)}const createButton=findCreateButton();if(!createButton){const observer=new MutationObserver(()=>{if(findCreateButton()){stableCreate();observer.disconnect()}});observer.observe(document.body,{childList:true,subtree:true});setTimeout(()=>observer.disconnect(),5000)}}

function patchWhatsapp(){const original=window.fetch.bind(window);window.fetch=async function(input,init={}){const url=typeof input==='string'?input:(input?.url||'');if(url.includes('/api/whatsapp-activate')&&init?.method==='POST'){const {data}=await supabase.auth.getSession();if(data?.session?.access_token)init={...init,headers:{...(init.headers||{}),Authorization:'Bearer '+data.session.access_token}}}return original(input,init)}}

function run(){if(location.pathname.endsWith('/ia-v2.html'))patchBuilder();if(location.pathname.endsWith('/whatsapp-config.html'))patchWhatsapp()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();