const SUPABASE_URL='https://uxmlmyhiagjefuufanyg.supabase.co';
const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
const TOKEN=process.env.ASAAS_WEBHOOK_TOKEN||'';
function out(res,s,b){res.setHeader('Content-Type','application/json');return res.status(s).json(b)}
async function sb(path,options={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json',Prefer:options.method==='POST'?'resolution=ignore-duplicates,return=representation':undefined,...(options.headers||{})}});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(`Supabase ${r.status}`);return p}
function clean(v){return String(v||'').trim().slice(0,250)}
export default async function handler(req,res){if(req.method!=='POST')return out(res,405,{error:'Método não permitido.'});if(!KEY||!TOKEN)return out(res,503,{error:'Webhook não configurado.'});const received=String(req.headers['asaas-access-token']||'');if(received!==TOKEN)return out(res,401,{error:'Não autorizado.'});try{const body=req.body||{},eventId=clean(body.id),event=clean(body.event);if(!eventId||!event)return out(res,400,{error:'Evento inválido.'});const inserted=await sb('billing_events',{method:'POST',body:JSON.stringify({provider:'asaas',provider_event_id:eventId,event_type:event,provider_resource_id:clean(body.payment?.id||body.subscription?.id||body.checkout?.id)})});if(!inserted?.length)return out(res,200,{ok:true,duplicate:true});const checkout=body.checkout||{},payment=body.payment||{},subscription=body.subscription||{};const external=clean(checkout.externalReference||payment.externalReference||subscription.externalReference);const providerSub=clean(subscription.id||payment.subscription);const providerCustomer=clean(checkout.customer||payment.customer||subscription.customer);let path='';if(external)path=`subscriptions?external_reference=eq.${encodeURIComponent(external)}&select=id,user_id,agent_id,status,provider_subscription_id,provider_customer_id&limit=1`;else if(providerSub)path=`subscriptions?provider_subscription_id=eq.${encodeURIComponent(providerSub)}&select=id,user_id,agent_id,status,provider_subscription_id,provider_customer_id&limit=1`;else if(providerCustomer)path=`subscriptions?provider_customer_id=eq.${encodeURIComponent(providerCustomer)}&select=id,user_id,agent_id,status,provider_subscription_id,provider_customer_id&limit=1`;if(!path)return out(res,200,{ok:true,ignored:true});const rows=await sb(path,{method:'GET'});if(!rows?.length)return out(res,200,{ok:true,unmatched:true});const current=rows[0];const patch={updated_at:new Date().toISOString()};if(providerSub)patch.provider_subscription_id=providerSub;if(providerCustomer)patch.provider_customer_id=providerCustomer;if(external)patch.external_reference=external;
const paid=['CHECKOUT_PAID','PAYMENT_RECEIVED','PAYMENT_CONFIRMED','PAYMENT_CONFIRMED_MANUALLY'].includes(event);const overdue=['PAYMENT_OVERDUE','PAYMENT_DUNNING_REQUESTED'].includes(event);const canceled=['PAYMENT_REFUNDED','PAYMENT_REFUND_IN_PROGRESS','PAYMENT_DELETED','SUBSCRIPTION_DELETED','SUBSCRIPTION_INACTIVATED'].includes(event);
if(event==='CHECKOUT_CREATED')patch.status='pending';if(paid)patch.status='active';if(overdue)patch.status='past_due';if(['PAYMENT_REFUNDED','PAYMENT_REFUND_IN_PROGRESS'].includes(event))patch.status='refunded';if(['PAYMENT_DELETED','SUBSCRIPTION_DELETED','SUBSCRIPTION_INACTIVATED'].includes(event))patch.status='canceled';if(['SUBSCRIPTION_CREATED','SUBSCRIPTION_UPDATED'].includes(event)&&subscription.status){const s=String(subscription.status).toUpperCase();patch.status=s==='ACTIVE'?'active':s==='EXPIRED'?'expired':s==='INACTIVE'?'canceled':current.status}if(subscription.nextDueDate)patch.current_period_end=subscription.nextDueDate;await sb(`subscriptions?id=eq.${encodeURIComponent(current.id)}`,{method:'PATCH',body:JSON.stringify(patch)});
if(current.agent_id){if(paid)await sb(`agents?id=eq.${encodeURIComponent(current.agent_id)}`,{method:'PATCH',body:JSON.stringify({status:'demo',whatsapp_status:'pending',updated_at:new Date().toISOString()})});if(overdue||canceled)await sb(`agents?id=eq.${encodeURIComponent(current.agent_id)}`,{method:'PATCH',body:JSON.stringify({status:'paused',updated_at:new Date().toISOString()})})}return out(res,200,{ok:true,agent_updated:!!current.agent_id,paid,ready_for_whatsapp:paid})}catch(e){console.error('Asaas webhook:',e);return out(res,500,{error:'Erro interno'})}}
