import crypto from 'node:crypto';
const SUPABASE_URL='https://uxmlmyhiagjefuufanyg.supabase.co',SERVICE_ROLE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||'',ANON_KEY=process.env.SUPABASE_ANON_KEY||SERVICE_ROLE_KEY,APP_ID=process.env.INSTAGRAM_APP_ID||'',APP_SECRET=process.env.INSTAGRAM_APP_SECRET||'',REDIRECT_URI=process.env.INSTAGRAM_REDIRECT_URI||'https://www.vencivo.com.br/api/instagram-callback',STATE_SECRET=process.env.INSTAGRAM_OAUTH_STATE_SECRET||'',SCOPES='instagram_business_basic,instagram_business_manage_messages,instagram_business_manage_comments';
function json(res,s,b){res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');return res.status(s).json(b)}
function html(res,s,title,message,ok=false){res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','no-store');const safe=String(message).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));return res.status(s).send(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · VENCIVO</title><style>body{margin:0;background:#070910;color:#f7f9fc;font:16px system-ui;display:grid;place-items:center;min-height:100vh}.card{width:min(520px,calc(100% - 32px));padding:28px;border:1px solid #ffffff16;border-radius:20px;background:#0d121e;text-align:center}a{display:inline-block;margin-top:18px;padding:11px 15px;border-radius:11px;background:linear-gradient(135deg,#63e6ff,#b0f7ff);color:#071018;text-decoration:none;font-weight:800}.ok{color:#57e6a8}.err{color:#ff9daa}</style></head><body><main class="card"><h1 class="${ok?'ok':'err'}">${safe}</h1><p>VENCIVO · Instagram</p><a href="/conta.html">Voltar para minha conta</a></main></body></html>`)}
function bearer(req){const h=String(req.headers.authorization||'');return h.startsWith('Bearer ')?h.slice(7).trim():''}
function state(userId){const p=Buffer.from(JSON.stringify({sub:userId,iat:Date.now(),exp:Date.now()+600000}),'utf8').toString('base64url');return p+'.'+crypto.createHmac('sha256',STATE_SECRET).update(p).digest('base64url')}
function verify(v){if(!STATE_SECRET||!v)return null;const [p,s]=String(v).split('.');if(!p||!s)return null;const e=crypto.createHmac('sha256',STATE_SECRET).update(p).digest('base64url');if(s.length!==e.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e)))return null;const d=JSON.parse(Buffer.from(p,'base64url').toString('utf8'));return d?.sub&&d?.exp>Date.now()?d:null}
async function user(token){const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:ANON_KEY,Authorization:`Bearer ${token}`}});return r.ok?r.json().catch(()=>null):null}
async function db(path,opt={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...opt,headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,...(opt.headers||{})}});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error('Falha ao salvar a conexão.');return p}
async function exchange(code){const body=new URLSearchParams({client_id:APP_ID,client_secret:APP_SECRET,grant_type:'authorization_code',redirect_uri:REDIRECT_URI,code});const r=await fetch('https://api.instagram.com/oauth/access_token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const p=await r.json().catch(()=>null);if(!r.ok||!p?.access_token)throw new Error('A troca do código do Instagram falhou.');return p}
async function longToken(t){const u=new URL('https://graph.instagram.com/access_token');u.searchParams.set('grant_type','ig_exchange_token');u.searchParams.set('client_secret',APP_SECRET);u.searchParams.set('access_token',t);const r=await fetch(u);const p=await r.json().catch(()=>null);if(!r.ok||!p?.access_token)throw new Error('Não foi possível obter o token de longa duração.');return p}
async function profile(t){const u=new URL('https://graph.instagram.com/me');u.searchParams.set('fields','id,username');u.searchParams.set('access_token',t);const r=await fetch(u);const p=await r.json().catch(()=>null);if(!r.ok||!p?.id)throw new Error('Não foi possível confirmar a conta do Instagram.');return p}
export default async function handler(req,res){try{const raw=String(req.url||''),path=raw.split('?')[0],q=req.query||{};const callback=path.endsWith('/instagram-callback')||String(q.callback||'')==='1';if(req.method!=='GET')return callback?html(res,405,'Método não permitido','Método não permitido.'):json(res,405,{error:'Método não permitido.'});if(!APP_ID||!STATE_SECRET||(callback&&!APP_SECRET))return callback?html(res,503,'Instagram não configurado','A conexão do Instagram ainda não está configurada no ambiente.'):json(res,503,{error:'Integração Instagram ainda não configurada no ambiente.'});if(!callback){const token=bearer(req);if(!token)return json(res,401,{error:'Faça login para conectar o Instagram.'});const u=await user(token);if(!u?.id)return json(res,401,{error:'Sessão inválida. Faça login novamente.'});const url=new URL('https://www.instagram.com/oauth/authorize');url.searchParams.set('client_id',APP_ID);url.searchParams.set('redirect_uri',REDIRECT_URI);url.searchParams.set('response_type','code');url.searchParams.set('scope',SCOPES);url.searchParams.set('state',state(u.id));return json(res,200,{authorization_url:url.toString(),redirect_uri:REDIRECT_URI,scopes:SCOPES.split(',')})}if(q.error)return html(res,200,'Conexão cancelada','A conexão com o Instagram foi cancelada.');const st=verify(q.state);if(!st)return html(res,400,'Link inválido','A autorização expirou ou é inválida. Volte ao VENCIVO e tente novamente.');const code=String(q.code||'').trim();if(!code)return html(res,400,'Código ausente','O Instagram não retornou o código de autorização.');const short=await exchange(code),long=await longToken(short.access_token),p=await profile(long.access_token),expiresAt=long.expires_in?new Date(Date.now()+Number(long.expires_in)*1000).toISOString():null;await db('instagram_connections',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify({owner_id:st.sub,instagram_user_id:String(p.id),username:p.username||null,access_token:long.access_token,token_expires_at:expiresAt,scopes:SCOPES.split(','),status:'active',updated_at:new Date().toISOString()})});return html(res,200,'Instagram conectado','Instagram conectado com sucesso.',true)}catch(e){console.error('Instagram:',e);const raw=String(req.url||''),callback=raw.split('?')[0].endsWith('/instagram-callback')||raw.includes('callback=1');return callback?html(res,400,'Não foi possível conectar',e?.message||'Não foi possível concluir a conexão com o Instagram.'):json(res,500,{error:'Não foi possível iniciar a conexão com o Instagram.'})}}
