import crypto from 'node:crypto';

const SUPABASE_URL='https://uxmlmyhiagjefuufanyg.supabase.co';
const SERVICE_ROLE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
const APP_ID=process.env.INSTAGRAM_APP_ID||'';
const STATE_SECRET=process.env.INSTAGRAM_OAUTH_STATE_SECRET||'';
const PUBLIC_URL=String(process.env.VENCIVO_PUBLIC_URL||'').replace(/\/$/,'');
const CALLBACK_PATH='/api/instagram-callback';
const SCOPES=['instagram_business_basic','instagram_business_manage_messages','instagram_business_manage_comments'];

function headers(res){res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Access-Control-Allow-Origin','https://vencivo.com.br');res.setHeader('Access-Control-Allow-Methods','GET,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');}
function json(res,status,body){headers(res);return res.status(status).json(body)}
async function authUser(req){const auth=String(req.headers.authorization||'');if(!auth.startsWith('Bearer ')||!SERVICE_ROLE_KEY)return null;try{const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SERVICE_ROLE_KEY,Authorization:auth}});if(!r.ok)return null;const u=await r.json();return u?.id?u:null}catch{return null}}
async function db(path,options={}){if(!SERVICE_ROLE_KEY)throw new Error('Supabase não configurado no servidor.');const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,'Content-Type':'application/json',Prefer:options.method==='POST'||options.method==='PATCH'?'return=representation':undefined,...(options.headers||{})}});const p=await r.json().catch(()=>null);if(!r.ok){console.error('Instagram Supabase error',r.status,p);throw new Error('Falha ao consultar os dados do Instagram.')}return p}
function signState(payload){const raw=Buffer.from(JSON.stringify(payload)).toString('base64url');const sig=crypto.createHmac('sha256',STATE_SECRET).update(raw).digest('base64url');return `${raw}.${sig}`}
export default async function handler(req,res){if(req.method==='OPTIONS'){headers(res);return res.status(204).end()}if(req.method!=='GET')return json(res,405,{error:'Método não permitido.'});try{if(!APP_ID||!STATE_SECRET||!PUBLIC_URL)return json(res,500,{error:'Instagram Login ainda não está configurado no servidor.'});const user=await authUser(req);if(!user)return json(res,401,{error:'Login necessário.'});const agentId=String(req.query?.agent_id||'').trim();if(!agentId)return json(res,400,{error:'Agente é obrigatório.'});const rows=await db(`agents?public_id=eq.${encodeURIComponent(agentId)}&owner_id=eq.${encodeURIComponent(user.id)}&select=public_id,owner_id,status&limit=1`);if(!rows?.length)return json(res,404,{error:'Agente não encontrado para esta conta.'});const exp=Math.floor(Date.now()/1000)+600;const state=signState({agent_id:agentId,user_id:user.id,exp});const redirectUri=`${PUBLIC_URL}${CALLBACK_PATH}`;const url=new URL('https://www.instagram.com/oauth/authorize');url.searchParams.set('client_id',APP_ID);url.searchParams.set('redirect_uri',redirectUri);url.searchParams.set('scope',SCOPES.join(','));url.searchParams.set('response_type','code');url.searchParams.set('state',state);return json(res,200,{authorize_url:url.toString(),redirect_uri:redirectUri,scopes:SCOPES})}catch(error){console.error('Instagram OAuth start:',error);return json(res,500,{error:error?.message||'Não foi possível iniciar a conexão com o Instagram.'})}}
