const SUPABASE_URL='https://uxmlmyhiagjefuufanyg.supabase.co';
const SERVICE_ROLE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
const GEMINI_KEY=process.env.GEMINI_API_KEY||'';
const KNOWLEDGE_BUCKET='vencivo-knowledge';
const KNOWLEDGE_MAX=50*1024*1024;
const KNOWLEDGE_TYPES={'.pdf':'application/pdf','.doc':'application/msword','.docx':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','.txt':'text/plain','.md':'text/markdown','.csv':'text/csv','.rtf':'text/rtf'};
function origin(req){const v=String(req.headers.origin||'').trim();const a=new Set(['https://vencivo.com.br','https://www.vencivo.com.br','https://vencivo-ai.vercel.app','http://localhost:3000','http://localhost:5173']);return a.has(v)?v:'https://vencivo.com.br'}
function headers(res,req){res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.setHeader('Access-Control-Allow-Origin',origin(req));res.setHeader('Access-Control-Allow-Methods','POST, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');res.setHeader('Vary','Origin')}
function json(res,req,status,body){headers(res,req);return res.status(status).json(body)}
function clean(v,max=600){return String(v??'').trim().slice(0,max)}
async function db(path,options={}){if(!SERVICE_ROLE_KEY)throw new Error('Supabase não configurado.');const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,'Content-Type':'application/json',Prefer:options.method==='POST'||options.method==='PATCH'?'return=representation':undefined,...(options.headers||{})}});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error('Falha ao persistir dados.');return p}
async function authUser(req){const a=String(req.headers.authorization||'');if(!a.startsWith('Bearer ')||!SERVICE_ROLE_KEY)return null;try{const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SERVICE_ROLE_KEY,Authorization:a}});if(!r.ok)return null;const u=await r.json();return u?.id?u:null}catch{return null}}
async function agent(req,id){const u=await authUser(req);const rows=await db(`agents?public_id=eq.${encodeURIComponent(id)}&status=in.(demo,active)&select=id,public_id,company_name,owner_id,knowledge_store_name`);const a=rows?.[0];if(!a)throw new Error('Agente não encontrado.');if(a.owner_id&&a.owner_id!==u?.id)throw new Error('Você não tem acesso a este agente.');return a}
function ext(name){const m=String(name||'').toLowerCase().match(/\.[a-z0-9]+$/);return m?m[0]:''}
async function signedUpload(path){const r=await fetch(`${SUPABASE_URL}/storage/v1/object/upload/sign/${KNOWLEDGE_BUCKET}/${path}`,{method:'POST',headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,'Content-Type':'application/json'},body:'{}'});const p=await r.json().catch(()=>null);if(!r.ok||!p?.url)throw new Error('Não foi possível preparar o upload.');return `${SUPABASE_URL}/storage/v1${p.url}`}
async function ensureStore(a){if(a.knowledge_store_name)return a.knowledge_store_name;if(!GEMINI_KEY)throw new Error('GEMINI_API_KEY não configurada.');const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/fileSearchStores?key=${encodeURIComponent(GEMINI_KEY)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({displayName:`VENCIVO · ${a.company_name} · ${a.public_id}`,embeddingModel:'models/gemini-embedding-2'})});const p=await r.json().catch(()=>null);if(!r.ok||!p?.name)throw new Error('Não foi possível criar a base inteligente.');await db(`agents?id=eq.${encodeURIComponent(a.id)}`,{method:'PATCH',body:JSON.stringify({knowledge_store_name:p.name})});return p.name}
async function processKnowledge(a,path,fileName,mime,size){if(!GEMINI_KEY)throw new Error('GEMINI_API_KEY não configurada.');const objectUrl=`${SUPABASE_URL}/storage/v1/object/authenticated/${KNOWLEDGE_BUCKET}/${path}`;const f=await fetch(objectUrl,{headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`}});if(!f.ok)throw new Error('Arquivo enviado não pôde ser lido.');const bytes=Buffer.from(await f.arrayBuffer());if(bytes.length>KNOWLEDGE_MAX)throw new Error('Arquivo acima de 50 MB.');const store=await ensureStore(a);const start=await fetch(`https://generativelanguage.googleapis.com/upload/v1beta/${store}:uploadToFileSearchStore?key=${encodeURIComponent(GEMINI_KEY)}`,{method:'POST',headers:{'X-Goog-Upload-Protocol':'resumable','X-Goog-Upload-Command':'start','X-Goog-Upload-Header-Content-Length':String(bytes.length),'X-Goog-Upload-Header-Content-Type':mime,'Content-Type':'application/json'},body:JSON.stringify({displayName:fileName,chunkingConfig:{whiteSpaceConfig:{maxTokensPerChunk:300,maxOverlapTokens:40}},customMetadata:[{key:'vencivo_agent_id',stringValue:a.public_id}]})});if(!start.ok)throw new Error('O Gemini recusou a preparação do documento.');const uploadUrl=start.headers.get('x-goog-upload-url')||start.headers.get('X-Goog-Upload-URL');if(!uploadUrl)throw new Error('O Gemini não retornou a URL de processamento.');const finish=await fetch(uploadUrl,{method:'PUT',headers:{'Content-Length':String(bytes.length),'X-Goog-Upload-Offset':'0','X-Goog-Upload-Command':'upload, finalize','Content-Type':mime},body:bytes});const operation=await finish.json().catch(()=>null);if(!finish.ok)throw new Error('O Gemini não conseguiu indexar o documento.');if(operation?.error)throw new Error('A indexação do documento falhou.');await db('agent_knowledge',{method:'POST',body:JSON.stringify({agent_id:a.id,file_name:fileName,content:'[Documento indexado no Gemini File Search]',content_type:mime,size_bytes:size||bytes.length})});await fetch(`${SUPABASE_URL}/storage/v1/object/${KNOWLEDGE_BUCKET}/${path}`,{method:'DELETE',headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`}}).catch(()=>{});return{store,agent_id:a.public_id,file_name:fileName,status:'ready'}}
export default async function handler(req,res){if(req.method==='OPTIONS'){headers(res,req);return res.status(204).end()}if(req.method!=='POST')return json(res,req,405,{error:'Método não permitido.'});try{const b=req.body||{},action=clean(b.action,20),id=clean(b.agent_id,80);if(!id)return json(res,req,400,{error:'Agente é obrigatório.'});if(action==='prepare'){const fileName=clean(b.file_name,160),mime=KNOWLEDGE_TYPES[ext(fileName)],size=Number(b.size||0);if(!mime)return json(res,req,400,{error:'Formato de arquivo não suportado.'});if(!size||size>KNOWLEDGE_MAX)return json(res,req,400,{error:'Arquivo inválido ou acima de 50 MB.'});const a=await agent(req,id),path=`${a.public_id}/${crypto.randomUUID()}-${fileName.replace(/[^a-zA-Z0-9._-]/g,'_')}`;return json(res,req,200,{path,mime,size,upload_url:await signedUpload(path)})}if(action==='process'){const path=clean(b.path,400),mime=clean(b.mime,120),fileName=clean(b.file_name,160),size=Number(b.size||0),a=await agent(req,id);if(!path.startsWith(`${a.public_id}/`))return json(res,req,403,{error:'Arquivo não pertence a este agente.'});return json(res,req,200,await processKnowledge(a,path,fileName||path.split('/').pop(),mime,size))}return json(res,req,400,{error:'Ação inválida.'})}catch(e){console.error('Knowledge API:',e);return json(res,req,500,{error:e?.message||'Não foi possível processar o documento agora.'})}}
