const SUPABASE_URL='https://uxmlmyhiagjefuufanyg.supabase.co';
const SERVICE_ROLE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
const GEMINI_KEY=process.env.GEMINI_API_KEY||'';
const BUCKET='vencivo-knowledge';
const MAX_BYTES=50*1024*1024;
const ALLOWED={
 '.pdf':'application/pdf','.doc':'application/msword','.docx':'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
 '.txt':'text/plain','.md':'text/markdown','.csv':'text/csv','.rtf':'text/rtf'
};
function origin(req){const o=String(req.headers.origin||'').trim();const a=new Set(['https://vencivo.com.br','https://www.vencivo.com.br','https://vencivo-ai.vercel.app','http://localhost:3000','http://localhost:5173']);return a.has(o)?o:'https://vencivo.com.br'}
function headers(res,req){res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.setHeader('Access-Control-Allow-Origin',origin(req));res.setHeader('Access-Control-Allow-Methods','POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,Authorization');res.setHeader('Vary','Origin')}
function out(res,req,status,body){headers(res,req);return res.status(status).json(body)}
function clean(v,max){return String(v??'').trim().slice(0,max)}
async function db(path,options={}){if(!SERVICE_ROLE_KEY)throw new Error('Supabase não configurado.');const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,'Content-Type':'application/json',Prefer:options.method==='PATCH'||options.method==='POST'?'return=representation':undefined,...(options.headers||{})}});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error('Falha no banco.');return p}
async function user(req){const a=String(req.headers.authorization||'');if(!a.startsWith('Bearer '))return null;const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SERVICE_ROLE_KEY,Authorization:a}}).catch(()=>null);return r?.ok?r.json():null}
async function agentFor(req,id){const u=await user(req);const rows=await db(`agents?public_id=eq.${encodeURIComponent(id)}&status=in.(demo,active)&select=id,public_id,company_name,owner_id,knowledge_store_name`);const a=rows?.[0];if(!a)throw new Error('Agente não encontrado.');if(a.owner_id&&a.owner_id!==u?.id)throw new Error('Você não tem acesso a este agente.');return a}
function ext(name){const m=String(name||'').toLowerCase().match(/\.[a-z0-9]+$/);return m?m[0]:''}
async function createStore(agent){if(agent.knowledge_store_name)return agent.knowledge_store_name;if(!GEMINI_KEY)throw new Error('GEMINI_API_KEY não configurada.');const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/fileSearchStores?key=${encodeURIComponent(GEMINI_KEY)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({displayName:`VENCIVO · ${agent.company_name} · ${agent.public_id}`,embeddingModel:'models/gemini-embedding-2'})});const p=await r.json().catch(()=>null);if(!r.ok||!p?.name)throw new Error('Não foi possível criar a base inteligente.');await db(`agents?id=eq.${encodeURIComponent(agent.id)}`,{method:'PATCH',body:JSON.stringify({knowledge_store_name:p.name})});return p.name}
async function signedUpload(path){const r=await fetch(`${SUPABASE_URL}/storage/v1/object/upload/sign/${BUCKET}/${path}`,{method:'POST',headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,'Content-Type':'application/json'},body:'{}'});const p=await r.json().catch(()=>null);if(!r.ok||!p?.url)throw new Error('Não foi possível preparar o upload.');const u=new URL(`${SUPABASE_URL}/storage/v1${p.url}`);return {url:u.toString(),path,token:u.searchParams.get('token')||''}}
async function processFile(agent,path,fileName,mime,size){if(!GEMINI_KEY)throw new Error('GEMINI_API_KEY não configurada.');const objectUrl=`${SUPABASE_URL}/storage/v1/object/authenticated/${BUCKET}/${path}`;const file=await fetch(objectUrl,{headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`}});if(!file.ok)throw new Error('Arquivo enviado não pôde ser lido.');const bytes=Buffer.from(await file.arrayBuffer());if(bytes.length>MAX_BYTES)throw new Error('Arquivo acima de 50 MB.');const store=await createStore(agent);const startUrl=`https://generativelanguage.googleapis.com/upload/v1beta/${store}:uploadToFileSearchStore?key=${encodeURIComponent(GEMINI_KEY)}`;const start=await fetch(startUrl,{method:'POST',headers:{'X-Goog-Upload-Protocol':'resumable','X-Goog-Upload-Command':'start','X-Goog-Upload-Header-Content-Length':String(bytes.length),'X-Goog-Upload-Header-Content-Type':mime,'Content-Type':'application/json'},body:JSON.stringify({displayName:fileName,chunkingConfig:{whiteSpaceConfig:{maxTokensPerChunk:300,maxOverlapTokens:40}},customMetadata:[{key:'vencivo_agent_id',stringValue:agent.public_id}]})});if(!start.ok)throw new Error('O Gemini recusou a preparação do documento.');const uploadUrl=start.headers.get('x-goog-upload-url')||start.headers.get('X-Goog-Upload-URL');if(!uploadUrl)throw new Error('O Gemini não retornou a URL de processamento.');const finish=await fetch(uploadUrl,{method:'PUT',headers:{'Content-Length':String(bytes.length),'X-Goog-Upload-Offset':'0','X-Goog-Upload-Command':'upload, finalize','Content-Type':mime},body:bytes});const op=await finish.json().catch(()=>null);if(!finish.ok)throw new Error('O Gemini não conseguiu indexar o documento.');let operation=op;for(let i=0;i<18&&operation&&!operation.done;i++){await new Promise(r=>setTimeout(r,1500));const name=operation.name;if(!name)break;const rr=await fetch(`https://generativelanguage.googleapis.com/v1beta/${name}?key=${encodeURIComponent(GEMINI_KEY)}`);operation=await rr.json().catch(()=>operation)}if(operation?.error)throw new Error('A indexação do documento falhou.');await db('agent_knowledge',{method:'POST',body:JSON.stringify({agent_id:agent.id,file_name:fileName,content:'[Documento indexado no Gemini File Search]',content_type:mime,size_bytes:size||bytes.length})});await fetch(`${SUPABASE_URL}/storage/v1/object/${BUCKET}/${path}`,{method:'DELETE',headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`}}).catch(()=>{});return {store,agent_id:agent.public_id,file_name:fileName,status:'ready'} }
export default async function handler(req,res){if(req.method==='OPTIONS'){headers(res,req);return res.status(204).end()}if(req.method!=='POST')return out(res,req,405,{error:'Método não permitido.'});try{const b=req.body||{},action=clean(b.action,20),id=clean(b.agent_id,80),fileName=clean(b.file_name,160);if(!id||!action)return out(res,req,400,{error:'agent_id e action são obrigatórios.'});const agent=await agentFor(req,id);if(action==='prepare'){const e=ext(fileName);const mime=ALLOWED[e];const size=Number(b.size||0);if(!mime)return out(res,req,400,{error:'Formato não suportado. Use PDF, DOC, DOCX, TXT, MD, CSV ou RTF.'});if(!size||size>MAX_BYTES)return out(res,req,400,{error:'Arquivo inválido ou acima de 50 MB.'});const safe=`${agent.public_id}/${crypto.randomUUID()}-${fileName.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const signed=await signedUpload(safe);return out(res,req,200,{path:safe,mime,size,upload_url:signed.url})}if(action==='process'){const path=clean(b.path,400),mime=clean(b.mime,120),size=Number(b.size||0);if(!path||!mime)return out(res,req,400,{error:'Dados de processamento incompletos.'});if(!path.startsWith(`${agent.public_id}/`))return out(res,req,403,{error:'Arquivo não pertence a este agente.'});const result=await processFile(agent,path,fileName||path.split('/').pop(),mime,size);return out(res,req,200,result)}return out(res,req,400,{error:'Ação inválida.'})}catch(e){console.error('Knowledge API:',e);return out(res,req,500,{error:e?.message||'Não foi possível processar a base de conhecimento.'})}}
